- init.d script now works for controlling all the configured ECE &   search instances as well as the rmi-hub:
  # /etc/init.d/ece status
  [ece#rmi-hub] down
  [ece#engine-rolling] down

  # /etc/init.d/ece start
  [ece#rmi-hub] starting the default instance of rmi-hub on quanah ...
  [ece#engine-rolling] starting the rolling instance of engine on quanah ...

  # /etc/init.d/ece status
  [ece#rmi-hub] up 0d 0h 0m 5s
  [ece#engine-rolling] up 0d 0h 0m 5s

- the ece script then produces the following log and PID files:
  /var/log/escenic/engine-rolling.out
  /var/log/escenic/rmi-hub.out
  /var/run/escenic/engine-rolling.pid
  /var/run/escenic/rmi-hub.pid

- added documentation to /etc/default/ece
- fixed a problem in stop_type where it would fail stopping the type
  if the instance hadn't been started with the ece script (but some
  other process/script).
- changed the configuration of rmi hub to be rmi_hub_enabled=true
  instead of start_rmi_hub=1

diff --git a/etc/init.d/ece b/etc/init.d/ece
--- a/etc/init.d/ece
+++ b/etc/init.d/ece
@@ -8,35 +8,35 @@
 ####################################################################
 # Default values
 ####################################################################
-start_rmi_hub=0
-engine_instance_list=default
-indexer_instance_list=""
-ece_unix_user=torstein
-ece_unix_group=torstein
-ece_script=/home/torstein/tmp/ece2
-
 dir_list="
 /var/log/escenic
 /var/run/escenic
 /var/cache/escenic
 "
 
-# may be overidden a file named the same as this init.d script,
-# located in:
+ece_script=/usr/bin/ece
+
+# the values above may be overidden a file named the same as this
+# init.d script, located in:
 conf_file_location_list="
 /etc/default
+/tmp
 "
 
 function read_conf_file()
 {
     for el in $conf_file_location_list; do
-        if [ -r $el/$1 ]; then
-            debug "found $1 in $el, reading it"
-            source $el/$1
+        if [ -r $el/`basename $0` ]; then
+            source $el/`basename $0`
+            found_conf=1
             break
         fi
-        
     done
+
+    if [ -z $found_conf ]; then
+        echo "Couldn't find configuration for $0, exiting :-("
+        exit 1
+    fi
 }
 
 function ensure_dirs_are_ok()
@@ -49,25 +49,38 @@ function ensure_dirs_are_ok()
     done
 }
 
+function ensure_ece_script_is_ok()
+{
+    if [ ! -r $ece_script ]; then
+        echo "Couldn't read $ece_script"
+        exit 1
+    elif [ ! -x $ece_script ]; then
+        echo "$ece_script needs to be executable (do: chmod +x $ece_script)"
+        exit 1
+    fi
+    
+}
+
 function execute_command()
 {
-    if [ $start_rmi_hub -eq 1 ]; then
-        $ece_script rmi-hub $2
+    if [ $enable_rmi_hub = "true" ]; then
+        $ece_script -t rmi-hub $1
     fi
     
     for el in $engine_instance_list; do
-        $ece_script $el $2
+        $ece_script -t engine -i $el $1
     done
     
-    for el in $indexer_instance_list; do
-        $ece_script $el $2
+    for el in $search_instance_list; do
+        $ece_script -t search -i $el $1
     done
 }
 
-if [ $2 ]; then
+if [ $1 ]; then
     read_conf_file
+    ensure_ece_script_is_ok
     ensure_dirs_are_ok
-    execute_command
+    execute_command $1
 else
     echo "Usage: `basename $0` <start|stop|restart|status>"
-done
+fi
