- made drop-and-create-ecedb safer by putting everything into   functions. - it's now sourced by ece-install and create_ecedb is called   explicitly

diff --git a/usr/sbin/drop-and-create-ecedb b/usr/sbin/drop-and-create-ecedb
--- a/usr/sbin/drop-and-create-ecedb
+++ b/usr/sbin/drop-and-create-ecedb
@@ -14,12 +14,12 @@
 # -torstein@escenic.com
 
 drop_db_first=0
-user=ece5user
-password=ece5password
-db=ece5db
-host=localhost
+db_user=ece5user
+db_password=ece5password
+db_schema=ece5db
+db_host=localhost
 ece_home=/opt/escenic/engine
-dbproduct=mysql
+db_product=mysql
 id="[`basename $0`]"
 
 # oracle specific settings
@@ -28,17 +28,35 @@ tablespace_data=ece5_data
 tablespace_index=ece5_index
 oracle_data_dir=/home/oracle/app/oracle/oradata/orcl
 
+debug=0
+
+function debug()
+{
+    if [ $debug -eq 1 ]; then
+        echo $id $1
+    fi
+    
+}
+
+function exit_on_error()
+{
+    if [ $? -eq 1 ]; then
+        echo $id $@ "FAILED, exiting :-("
+        exit 1
+    fi
+}
+
 function create_oracle_ece_user() {
     sqlplus /nolog << EOF
       connect /as sysdba;
-      create user $user
-        identified by $password
+      create user $db_user
+        identified by $db_password
         default tablespace $tablespace_data
         quota unlimited on $tablespace_data;
-      grant connect to $user;
-      grant resource to $user;
-      grant create any view to $user;
-      grant execute on ctx_ddl to $user;
+      grant connect to $db_user;
+      grant resource to $db_user;
+      grant create any view to $db_user;
+      grant execute on ctx_ddl to $db_user;
 EOF
 }
 
@@ -46,62 +64,68 @@ function run_db_scripts()
 {
     for el in $db_fn_list; do
         file=$1/$el.sql
-        echo $id "running $file ..."
+        debug "running $file ..."
         if [ -e $1/$el.sql ]; then
-            if [ $dbproduct = "oracle" ]; then
-                sqlplus $user/$password @$file
+            if [ $db_product = "oracle" ]; then
+                sqlplus $db_user/$db_password @$file
             else
-                mysql -u $user -p$password -h $host $db < $file
+                mysql -u $db_user -p$db_password -h $db_host $db_schema < $file
             fi
         fi
+        exit_on_error "running $el"
     done
 }
 
-if [ $create_oracle_user -eq 1 ]; then
-    create_oracle_ece_user
-fi
+function pre_install_new_ecedb()
+{
+    if [ $create_oracle_user -eq 1 ]; then
+        create_oracle_ece_user
+    fi
 
-if [ $drop_db_first -eq 1 ]; then
-    echo $id "dropping and re-creating $db on $host ..."
-    if [ $dbproduct = "mysql" ]; then
-        mysql -h $host << EOF
-          drop database $db;
+    if [ $drop_db_first -eq 1 ]; then
+        debug "dropping and re-creating $db_schema on $db_host ..."
+        if [ $db_product = "mysql" ]; then
+            mysql -h $db_host << EOF
+drop database $db_schema;
+EOF
+        else
+            sqlplus /nolog << EOF
+connect /as sysdba;
+drop tablespace $tablespace_data including contents;
+drop tablespace $tablespace_index including contents;
+EOF
+        fi
+    fi
+}
+    
+function create_schema()
+{
+    # we first create the DB (or, if drop_db_first is 1, we've just
+    # dropped it above) before running the SQL scripts.
+    if [ $db_product = "mysql" ]; then
+        mysql -h $db_host << EOF
+create database $db_schema character set utf8 collate utf8_general_ci;
+grant all on $db_schema.* to $db_user@'%' identified by '$db_password';
+grant all on $db_schema.* to $db_user@'localhost' identified by '$db_password';
 EOF
     else
         sqlplus /nolog << EOF
-          connect /as sysdba;
-          drop tablespace $tablespace_data including contents;
-          drop tablespace $tablespace_index including contents;
+connect /as sysdba;
+  
+create tablespace $tablespace_data 
+datafile '$oracle_data_dir/${tablespace_data}01.dbf'
+size 200M reuse
+autoextend on next 50M maxsize 2047M
+extent management local autoallocate;
+
+create tablespace $tablespace_index
+datafile '$oracle_data_dir/${tablespace_index}01.dbf'
+size 100M reuse
+autoextend on next 50M maxsize 2047M
+extent management local autoallocate;          
 EOF
     fi
-fi
-
-# we first create the DB (or, if drop_db_first is 1, we've just
-# dropped it above) before running the SQL scripts.
-if [ $dbproduct = "mysql" ]; then
-    mysql -h $host << EOF
-        create database $db character set utf8 collate utf8_general_ci;
-        grant all on $db.* to $user@'%' identified by '$password';
-        grant all on $db.* to $user@'localhost' identified by '$password';
-EOF
-else
-    sqlplus /nolog << EOF
-        connect /as sysdba;
-          
-        create tablespace $tablespace_data 
-        datafile '$oracle_data_dir/${tablespace_data}01.dbf'
-        size 200M reuse
-        autoextend on next 50M maxsize 2047M
-        extent management local autoallocate;
-
-        create tablespace $tablespace_index
-        datafile '$oracle_data_dir/${tablespace_index}01.dbf'
-        size 100M reuse
-        autoextend on next 50M maxsize 2047M
-        extent management local autoallocate;          
-EOF
-fi
-
+}
 
 db_fn_list="
 tables
@@ -114,10 +138,19 @@ indexes
 history
 "
 
-run_db_scripts $ece_home/database/$dbproduct
+function create_ecedb()
+{
+    create_schema
+    run_db_scripts $ece_home/database/$db_product
 
-for el in `find -L $ece_home/plugins -name $dbproduct`; do
-    run_db_scripts $el
-done
+    if [ -e $ece_home/plugins ]; then
+        for el in `find -L $ece_home/plugins -name $db_product`; do
+            run_db_scripts $el
+        done
+    fi
 
-echo "${id} ${dbproduct}://${host}/${db} is now ready for ${user}/${password}"
+    echo "${id} ${db_product}://${db_host}/${db_schema} is now ready for ${db_user}/${db_password}"
+}
+
+# pre_install_new_ecedb
+# create_ecedb
