- moved all cache server related code to ece-install.d/cache-server.sh - added loading of ece-install.d modules and common libraries to new   method, init() - clean-up/faster install on Debian based systems:   * will not fetch and add the varnish APT key if already exists     in the local key ring.   * will not add the varnish APT source to escenic.list if already     exists in sources.list

diff --git a/usr/sbin/ece-install b/usr/sbin/ece-install
--- a/usr/sbin/ece-install
+++ b/usr/sbin/ece-install
@@ -108,14 +108,33 @@ PROFILE_MONITORING_SERVER=10
 PROFILE_RESTORE_FROM_BACKUP=11
 PROFILE_ANALYSIS_SERVER=12
 
-######################################################################
-# Load common BASH libraries
-######################################################################
-common_libraries="common-bashing.sh common-pulse.sh common-io.sh common-os.sh"
-for el in $common_libraries; do
-  source $(dirname $0)/../share/escenic/ece-scripts/${el} || \
-    (echo "Could not find $el"; exit 1)
-done
+## Bootstrapping, load files from /usr/share/escenic/ece-scripts The
+## method will first try to be smart, in case the user has copied the
+## ece-scripts somewhere else., e.g.: moved everything to ~/ece-scrpts
+## or /opt/escenic/ece-scripts, this should also work.
+function init() {
+  # first, try to be nice
+  local dir=$(dirname $0)/../share/escenic/ece-scripts
+
+  # then check the standard location
+  if [ ! -d $dir  ]; then
+    dir=/usr/share/escenic/ece-scripts
+  fi
+
+  if [ -d $dir ]; then
+    # load common librariees
+    common_libraries="common-bashing.sh common-pulse.sh common-io.sh common-os.sh"
+    for el in $common_libraries; do
+      source $dir/${el}
+    done
+
+    # load ece-install modules
+    source $dir/ece-install.d/*.sh
+  else
+    echo "I cannot find $(basename $0)'s dependencies, exiting :-("
+    exit 1
+  fi
+}
 
 function set_up_engine_directories()
 {
@@ -1292,7 +1311,7 @@ function print_status_and_next_steps()
     seconds_left=$(( seconds_left - $minutes * 60 ))
 
     if [ $install_profile_number -ne $PROFILE_RESTORE_FROM_BACKUP ]; then
-        s="The installation is now complete!"
+        s="The installation is now $(green complete)!"
     else
         s="The restore is now complete!"
     fi
@@ -1539,147 +1558,6 @@ function get_privileged_hosts() {
   echo ${privileged_hosts}
 }
 
-function set_up_varnish()
-{
-    print_and_log "Setting up Varnish to match your environment ..."
-    run /etc/init.d/varnish stop
-
-    # we need to swap standard err and standard out here as varnishd
-    # -V for some reason writes to standard error.
-    using_varnish_3=$(varnishd -V 3>&1 1>&2 2>&3 | grep varnish-3 | wc -l)
-    
-    local file=/etc/default/varnish
-    sed -i -e 's/6081/80/g' -e 's/^START=no$/START=yes/' $file
-    exit_on_error "sed on $file"
-
-    cat > /etc/varnish/default.vcl <<EOF
-/* Varnish configuration for Escenic Content Engine              -*- java -*- */
-
-/* IPs that are allowed to access the administrative pages/webapps. */
-acl staff {
-  "localhost";
-EOF
-    for l in $(get_privileged_hosts); do
-        cat >> /etc/varnish/default.vcl <<EOF
-  # Privileged host (either doing the ece-install or listed as such)
-  "${l}";
-EOF
-    done
-    
-    cat >> /etc/varnish/default.vcl <<EOF
-}
-
-/* The IP of the Adactus/Mobilize server */
-acl adactus {
-  "203.33.232.216";
-}
-
-/* Our web server for serving static content */
-backend static {
-  .host = "localhost";
-  .port = "81";
-}
-
-EOF
-    for el in $backend_servers; do
-        appserver_id=$(echo $el | cut -d':' -f1 | sed 's/-/_/g')
-        appserver_host=$(echo $el | cut -d':' -f1)
-        appserver_port=$(echo $el | cut -d':' -f2)
-
-        cat >> /etc/varnish/default.vcl <<EOF
-backend $appserver_id {
-  .host = "$appserver_host";
-  .port = "$appserver_port";
-}
-
-EOF
-    done
-
-    cat >> /etc/varnish/default.vcl <<EOF
-/* The client director gives us session stickiness based on client
- * IP. */
-director webdirector client {
-EOF
-    for el in $backend_servers; do
-	      appserver_id=$(echo $el | cut -d':' -f1 | sed 's/-/_/g' )        
-        cat >> /etc/varnish/default.vcl <<EOF
-  {
-     .backend = $appserver_id;
-     .weight = 1;
-  }
-EOF
-    done
-
-    cat >> /etc/varnish/default.vcl <<EOF
-}
-
-sub vcl_recv {
-  if (!client.ip ~ staff &&
-      (req.url ~ "^/escenic" ||
-       req.url ~ "^/studio" ||
-       req.url ~ "^/munin" ||
-       req.url ~ "^/webservice" ||
-       req.url ~ "^/escenic-admin")) {
-     error 405 "Not allowed.";
-  }
-
-  /* Only Adactus/Mobilize is allowed to access the /binary context
-   * which contains all the full quality video files. */
-  if (!client.ip ~ adactus && req.url ~ "^/binary") {
-    error 405 "Not allowed.";
-  }
-
-  if (req.url ~ "^/munin") {
-    set req.url = regsub(req.url, "^/munin", "/");
-    set req.backend = static;
-  }
-  else {
-    set req.backend = webdirector;
-  }
-
-  if (req.url ~ "\.(png|gif|jpg|css|js)$" || req.url == "/favicon.ico") { 
-    remove req.http.Cookie;
-  }
-}
-
- /* Called when content is fetched from the backend. */
-sub vcl_fetch {
-  /* Remove cookies from these resource types and cache them for a
-   * long time */
-  if (req.url ~ "\.(png|gif|jpg|css|js)$" || req.url == "/favicon.ico") { 
-    set beresp.ttl = 5h;
-    remove beresp.http.Set-Cookie;
-  }
-}
-
-sub vcl_deliver {
-  /* Adds debug header to the result so that we can easily see if a
-   * URL has been fetched from cache or not.
-   */
-  if (obj.hits > 0) {
-EOF
-    if [ $using_varnish_3 -gt 0 ]; then
-        cat >> /etc/varnish/default.vcl <<EOF
-    set resp.http.X-Cache = "HIT #" + obj.hits;
-EOF
-    else
-        cat >> /etc/varnish/default.vcl <<EOF
-    set resp.http.X-Cache = "HIT #" obj.hits;
-EOF
-    fi
-    
-    cat >> /etc/varnish/default.vcl <<EOF
-  }
-  else {
-    set resp.http.X-Cache = "MISS";
-  }
-
-  set resp.http.X-Cache-Backend = req.backend;
-}
-EOF
-    run /etc/init.d/varnish start
-}
-
 function read_user_input()
 {
     installation_profiles=(
@@ -1812,65 +1690,14 @@ function common_pre_install()
 function add_apt_source()
 {
     escenic_sources=/etc/apt/sources.list.d/escenic.list
-    if [ ! -e $escenic_sources ]; then
+    if [[ ! -e $escenic_sources &&
+          $(grep "$@" /etc/apt/sources.list | wc -l) -lt 1 ]]; then
         echo "$@" >> $escenic_sources
         run apt-get update
     elif [ $(grep "$@" $escenic_sources | wc -l) -lt 1 ]; then
         echo "$@" >> $escenic_sources
         run apt-get update
     fi
-}
-
-function install_cache_server()
-{
-    print_and_log "Installing a caching server on $HOSTNAME ..."
-
-    if [ $on_debian_or_derivative -eq 1 ]; then
-        curl ${curl_opts} \
-            http://repo.varnish-cache.org/debian/GPG-key.txt \
-            2>> $log | \
-            apt-key add - \
-            1>>$log 2>>$log
-        run apt-get update
-    fi
-
-    code_name=$(lsb_release -s -c)
-    
-    supported_code_name=0
-    # list taken from http://repo.varnish-cache.org/debian/dists/
-    supported_list="lenny squeeze hardy lucid"
-    for el in $supported_list; do
-        if [ $code_name = $el ]; then
-            supported_code_name=1
-        fi
-    done
-    
-    if [ $supported_code_name -eq 1 -a $on_debian -eq 1 ]; then
-        add_apt_source "deb http://repo.varnish-cache.org/debian/ $(lsb_release -s -c) varnish-3.0"
-    elif [ $supported_code_name -eq 1 -a $on_ubuntu -eq 1 ]; then
-        add_apt_source "deb http://repo.varnish-cache.org/ubuntu/ $(lsb_release -s -c) varnish-3.0"
-    fi
-
-    install_packages_if_missing varnish
-    assert_pre_requisite varnishd
-
-    if [ $fai_enabled -eq 0 ]; then
-        print "You must now list your backend servers."
-        print "Seperate the entries with a space. e.g.: app1:8080 app2:8080."
-        print "Press ENTER to accept the default: ${HOSTNAME}:${appserver_port}"
-        echo -n "Your choice [${HOSTNAME}:${appserver_port}]> "
-        read backend_servers
-    else
-        backend_servers=$(get_conf_value fai_cache_backends)
-    fi
-
-    if [ -z "$backend_servers" ]; then
-        backend_servers="${HOSTNAME}:${appserver_port}"
-    fi
-
-    set_up_varnish $backend_servers
-
-    add_next_step "Cache server is up and running at http://${HOSTNAME}:80/"
 }
 
 # Parameters:
@@ -3089,14 +2916,14 @@ function restore_from_backup()
         gunzip < $sql_file | mysql $db_schema
         exit_on_error "restoring from $sql_file"
         
-        add_next_step "Successfully restored DB from $(basename $sql_file)"
+        add_next_step "$(green Successfully) restored DB from $sql_file"
     fi
     
     if [ $restore_data_files -eq 1 -o $restore_all -eq 1 ]; then
         print_and_log "Restoring the Solr & ECE data files on $HOSTNAME ..."
         run cd $dir
         run tar -C / -xf $backup_file var/lib/escenic
-        add_next_step "Successfully restored Solr & ECE data files"
+        add_next_step "$(green Successfully) restored Solr & ECE data files"
         add_next_step "Backup file used:  $(basename $backup_file)"
         add_next_step "Check $escenic_data_dir to verify they're all there."
     fi
@@ -3105,7 +2932,7 @@ function restore_from_backup()
         print_and_log "Restoring the ECE configuration files on $HOSTNAME ..."
         run cd $dir
         run tar -C / -xf $backup_file etc
-        add_next_step "Successfully restored ECE configuration files"
+        add_next_step "$(green Successfully) restored ECE configuration files"
         add_next_step "Backup file used: $(basename $backup_file)"
         add_next_step "Check /etc to verify that they're all there."
     fi
@@ -3114,7 +2941,7 @@ function restore_from_backup()
         print_and_log "Restoring the Escenic & Tomcat binaries on $HOSTNAME ..."
         run cd $dir
         run tar -C / -xf $backup_file opt
-        add_next_step "Successfully restored Escenic & Tomcat binaries"
+        add_next_step "$(green Successfully) restored Escenic & Tomcat binaries"
         add_next_step "Backup file used: $(basename $backup_file)"
         add_next_step "Check ${appserver_parent_dir} to verify that they're all there".
         install_ece_third_party_packages
@@ -3268,6 +3095,7 @@ for el in $@; do
     fi
 done
 
+init
 assert_correct_runtime_environment
 
 fai_enabled=$(get_boolean_conf_value fai_enabled)
