- first working version of ece-import, juhu!
  Given two import XML files from a third party source, such as video
  meta data:

    /var/spool/escenic/raw/mypub/video/video.xml
    /var/spool/escenic/raw/mypub/video/arne.xml

  and publication=mypub and import job name=video, the script is
  invoked like:

    $ ece-import --name video --publication mypub
    [ece-import-0] Started @ Tue Oct 23 16:31:29 CEST 2012
    [ece-import-0] I'm logging to /var/log/escenic/ece-import.log
    [ece-import-0] Running the import job video
    [ece-import-0] Importing raw XML #1: arne.xml ...
    [ece-import-0] Importing raw XML #2: video.xml ...
    [ece-import-0] Finished @ Tue Oct 23 16:31:29 CEST 2012

  As you may have guessed, the log file has more details:

    [ece-import-0] Started @ Tue Oct 23 16:31:29 CEST 2012
    [ece-import-0] Running the import job video
    [ece-import-0] Importing raw XML #1: arne.xml ...
    [ece-import-0] Applying transformation 01-add-line-break.sh to /var/spool/escenic/raw/mypub/video/arne.xml
    [ece-import-0] Applying transformation 02-select-name-element.xsl to /var/spool/escenic/raw/mypub/video/arne.xml
    [ece-import-0] Applying transformation 03-add-date-in-comment.sh to /var/spool/escenic/raw/mypub/video/arne.xml
    [ece-import-0] Applying transformation 04-massage-xml.sh to /var/spool/escenic/raw/mypub/video/arne.xml
    [ece-import-0] Applying transformation 05-kissed-by-a-python.py /var/spool/escenic/raw/mypub/video/arne.xml
    [ece-import-0] Applied transformations to /var/spool/escenic/raw/mypub/video/arne.xml
    [ece-import-0] Moving /var/spool/escenic/raw/mypub/video/arne.xml to /var/spool/escenic/import/mypub/video/new/arne.xml
    [ece-import-0] Importing raw XML #2: video.xml ...
    [ece-import-0] Applying transformation 01-add-line-break.sh to /var/spool/escenic/raw/mypub/video/video.xml
    [ece-import-0] Applying transformation 02-select-name-element.xsl to /var/spool/escenic/raw/mypub/video/video.xml
    [ece-import-0] Applying transformation 03-add-date-in-comment.sh to /var/spool/escenic/raw/mypub/video/video.xml
    [ece-import-0] Applying transformation 04-massage-xml.sh to /var/spool/escenic/raw/mypub/video/video.xml
    [ece-import-0] Applying transformation 05-kissed-by-a-python.py /var/spool/escenic/raw/mypub/video/video.xml
    [ece-import-0] Applied transformations to /var/spool/escenic/raw/mypub/video/video.xml
    [ece-import-0] Moving /var/spool/escenic/raw/mypub/video/video.xml to /var/spool/escenic/import/mypub/video/new/video.xml
    [ece-import-0] Finished @ Tue Oct 23 16:31:29 CEST 2012

  This import can be automated by having one cron entry per import
  job, they will all call the ece-import script with different
  parameters.

- ece-import itself only returns code=1 (error) if there's something
  wrong with the setup of the import jobs. Errors in the
  transformations of the import data files are flagged as ERROR in the
  log, but ece-import itself doesn't exit in error, but continues onto
  the next import data file.

- ece-import uses common libraries such as common-os.sh and
  common-io.sh

diff --git a/usr/bin/ece-import b/usr/bin/ece-import
--- a/usr/bin/ece-import
+++ b/usr/bin/ece-import
@@ -4,6 +4,9 @@
 ## the standard Escenic Syndication XML import job.
 ##
 ## The script can also create an import job from an import job archive
+## 
+##  See /usr/share/doc/vizrt/vosa-handbook/import-jobs.org for more
+##  details on the structures this command operates on.
 
 common_libraries="
   /usr/share/escenic/ece-scripts/common-bashing.sh
@@ -35,18 +38,24 @@ command=COMMAND_IMPORT
 function get_user_input() {
   local next_is_name=0
   local next_is_publication=0
+  local next_is_conf_file=0
   
   for el in $@; do
     if [[ "$el" == "-n" || "$el" == "--name" ]]; then
       next_is_name=1
     elif [[ "$el" == "-p" || "$el" == "--publication" ]]; then
       next_is_publication=1
+    elif [[ "$el" == "-f" || "$el" == "--conf-file" ]]; then
+      next_is_conf_file=1
     elif [ $next_is_name -eq 1 ]; then
       job_name=$el
       next_is_name=0
     elif [ $next_is_publication -eq 1 ]; then
       publication_name=$el
       next_is_publication=0
+    elif [ $next_is_conf_file -eq 1 ]; then
+      conf_file=$el
+      next_is_conf_file=0
     else
       if [[ "$el" == "create" ]]; then
         command=COMMAND_CRETAE_IMPORT_CONFIGURATION
@@ -54,9 +63,23 @@ function get_user_input() {
     fi
   done
 
+  local errors=0
   if [ -z $job_name ]; then
     print_and_log "You must specify which import job to run"
     print_and_log "E.g.: $(basename $0) --name video"
+    errors=1
+  fi
+  if [ -z $publication_name ]; then
+    print_and_log "You must specify the publication name"
+    print_and_log "E.g.: $(basename $0) --publication mypub"
+    errors=1
+  fi
+  if [ -n "${conf_file}" -a ! -r "${conf_file}" ]; then
+    print_and_log "You have specified a print job conf file" \
+      "but it doesn't exist :-()"
+    remove_pid_and_exit_in_error
+  fi
+  if [ $errors -eq 1 ]; then
     remove_pid_and_exit_in_error
   fi
 
@@ -81,6 +104,7 @@ function check_pre_requisites() {
 
   local required_command_list="
     xsltproc
+    xmllint
   "
   
   for el in $required_command_list; do
@@ -90,63 +114,107 @@ function check_pre_requisites() {
       remove_pid_and_exit_in_error
     fi
   done
-
-  if [ ! -d $transformers_base_dir/$job_name ]; then
-    print_and_log $transformers_base_dir/$job_name "doesn't exist :-("
-    remove_pid_and_exit_in_error
-  fi
-
-  for el in new archive error; do
-    local dir=$escenic_spool_base_dir/$job_name/$el
-    if [ ! -d ${dir} ]; then
-      print_and_log ${dir} "doesn't exist, I will try to create it."
-      make_dir ${dir}
-    fi
-  done
-
 }
 
+## $1 :: file
 function perform_transformations() {
-  find $raw_spool_base_dir/$job_name -type f | while read f; do
-    print_and_log "Importing raw XML $f ..."
-    local i=0
-    for el in $transformers_base_dir/$job_name/[0-9]*; do
-      if [[ "$el" == *".sh" ]]; then
-        log "Applying transformation $(basename $el) to $f"
-        echo bash $el $f
-      elif [[ "$el" == *".xsl" ]]; then
-        log "Applying transformation $(basename $el) to $f"
-        echo xsltproc --output $(basename $f).tmp $el $f 
-        echo run mv $(basename $f).tmp $(basename $f)
-      elif [[ "$el" == *".pl" ]]; then
-        log "Applying transformation $(basename $el) to $f"
-        echo perl $el $f
-      elif [[ "$el" == *".py" ]]; then
-        log "Applying transformation $(basename $el) $f"
-        echo python $el $f
+  local i=0
+  for el in $transformers_base_dir/$publication_name/$job_name/[0-9]*; do
+    if [[ "$el" == *".sh" ]]; then
+      log "Applying transformation $(basename $el) to $1"
+      bash $el $1 >> $log 2>> $log
+      
+      if [ $? -gt 0 ]; then
+        log "$(red FAILED) The transformation $el on file $1" \
+          "moving $1 to the error directory and skipping to next import XML"
+        run mv $1 $escenic_spool_base_dir/$publication_name/$job_name/error
+        return
       fi
-      i=$(( i + 1 ))
-    done
-
-    log "Applied $i transformations to $f, moving it to " \
-      $escenic_spool_base_dir/$job_name/new
-    echo run mv $f $escenic_spool_base_dir/$job_name/new
+    elif [[ "$el" == *".xsl" ]]; then
+      log "Applying transformation $(basename $el) to $1"
+      xsltproc --output ${1}.tmp ${el} ${1} >> $log 2>> $log
+      
+      if [ $? -gt 0 ]; then
+        log "$(red FAILED) The transformation $el on file $1" \
+          "moving $1 to the error directory and skipping to next import XML"
+        run mv $1 $escenic_spool_base_dir/$publication_name/$job_name/error
+        return
+      else
+        run mv ${1}.tmp ${1}
+      fi
+    elif [[ "$el" == *".pl" ]]; then
+      log "Applying transformation $(basename $el) to $1"
+      perl $el $1 >> $log 2>> $log
+      if [ $? -gt 0 ]; then
+        log "$(red FAILED) The transformation $el on file $1" \
+          "moving $f to the error directory and skipping to next import XML"
+        run mv $1 $escenic_spool_base_dir/$publication_name/$job_name/error
+        return
+      fi
+    elif [[ "$el" == *".py" ]]; then
+      log "Applying transformation $(basename $el) $1"
+      python $el $f >> $log 2>> $log
+      if [ $? -gt 0 ]; then
+        log "$(red FAILED) The transformation $el on file $1" \
+          "moving $1 to the error directory and skipping to next import XML"
+        run mv $1 $escenic_spool_base_dir/$publication_name/$job_name/error
+        return
+      fi
+    fi
+    i=$(( i + 1 ))
   done
+}
+
+function import_raw_files() {
+  raw_file_count=0
+  for f in $(find $raw_spool_base_dir/$publication_name/$job_name -type f); do
+    raw_file_count=$(( raw_file_count + 1 ))
+    print_and_log "Importing raw XML #${raw_file_count}: $(basename $f) ..."
+    perform_transformations $f
+
+    log "Applied $i transformations to $f"
+    if [ $(check_escenic_xml $f) -eq 0 ]; then
+      log "Moving $f to" \
+        $escenic_spool_base_dir/$publication_name/$job_name/new/$(basename $f)
+      run mv $f $escenic_spool_base_dir/$publication_name/$job_name/new
+    fi
+  done
+}
+
+## $1 :: the XML
+function check_escenic_xml() {
+  if [ ! -e $1 ]; then
+    echo 1
+    return
+  fi
+  
+  xmllint --format $1 > /dev/null 2>&1
+  if [ $? -gt 0 ]; then
+    log $(yellow WARNING) "XML #${raw_file_count} after transformations," \
+      $f "isn't well formed XML. Importing it into Escenic Content Engine" \
+      " will fail, so I'll move it to" \
+      $escenic_spool_base_dir/$publication_name/$job_name/error
+    run mv $1 $escenic_spool_base_dir/$publication_name/$job_name/error
+    echo 1
+    return
+  fi
+
+  echo 0
 }
 
 function verify_import_job_configuration() {
   verify_writable_dir_list \
-    $raw_spool_base_dir/$job_name \
-    $escenic_spool_base_dir/$job_name/new \
-    $escenic_spool_base_dir/$job_name/archive \
-    $escenic_spool_base_dir/$job_name/error
-  verify_readable_dir_list $transformers_base_dir/$job_name
+    $raw_spool_base_dir/$publication_name/$job_name \
+    $escenic_spool_base_dir/$publication_name/$job_name/new \
+    $escenic_spool_base_dir/$publication_name/$job_name/archive \
+    $escenic_spool_base_dir/$publication_name/$job_name/error
+  verify_readable_dir_list $transformers_base_dir/$publication_name/$job_name
 
   local tranformation_count=$(
-    ls $transformers_base_dir/$job_name | \
-    grep ^[0-9] | \
-    egrep ".sh$|.pl|.py" | \
-    wc -l
+    ls $transformers_base_dir/$publication_name/$job_name | \
+      grep ^[0-9] | \
+      egrep ".sh$|.pl|.py" | \
+      wc -l
   )
   
   if [ $tranformation_count -lt 1 ]; then
@@ -162,6 +230,6 @@ print_and_log "Started @ $(date)"
 print "I'm logging to $log"
 get_user_input "$@"
 verify_import_job_configuration
-perform_transformations
+import_raw_files
 print_and_log "Finished @ $(date)"
 remove_pid_if_exists $pid_file
