- vosa-cat is now smarter when diff local files in the user's SCM   copy. It will try to find the file in question by first testing:
  Given the call:

    $ vosa-cat -s ~/src/nie/server-admin -f etc/fstab -i pres1

  It will locate the file in this order:

    1)  ~/src/nie/server-admin/etc/fstab
    2)  ~/src/nie/server-admin/common/etc/fstab
    3)  ~/src/nie/server-admin/pres1/etc/fstab

diff --git a/usr/bin/vosa-cat b/usr/bin/vosa-cat
--- a/usr/bin/vosa-cat
+++ b/usr/bin/vosa-cat
@@ -70,9 +70,23 @@ function cat_vosa_file() {
   fi
 }
 
+function get_scm_file() {
+  local file=$scm_dir/$vosa_input_file
+  if [ -e $file ]; then
+    echo $file
+  elif [ -e $scm_dir/$instance/$vosa_input_file ]; then
+    echo $scm_dir/$instance/$vosa_input_file
+  elif [ -e $scm_dir/common/$vosa_input_file ]; then
+    echo $scm_dir/common/$vosa_input_file
+  else
+    echo $vosa_input_file "couldn't be found under $scm_dir"
+    exit 1
+  fi
+}
+
 function diff_vosa_file() {
   local vosa_file=$(get_vosa_file)
-  diff $vosa_file $scm_dir/$vosa_input_file
+  diff $vosa_file $(get_scm_file)
 }
 
 function remote_vosa_diff() {
